version: 0.1

phase:
  build:
    commands:
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - Resume.pdf
    - images/*
    - styles/*
    - scripts/*
    - dist/bundle.js